services:
  main_interface:
    build:
      context: .
      dockerfile: ./main/Dockerfile
    volumes:
      - ./data:/app/data
      - ./main:/app/main
      - ./tests:/app/tests
      - ./src:/app/src
    ports:
      - "8080:8080"
    depends_on:
      - bcause_solver

  lcn_solver:
    build:
      context: .
      dockerfile: ./src/solvers/lcn_solver/Dockerfile
    volumes:
      - ./data:/app/data
    ports:
      - "5001:5001"

  dowhy_solver:
    build:
      context: .
      dockerfile: ./src/solvers/dowhy_solver/Dockerfile
    volumes:
      - ./data:/app/data
    ports:
      - "5002:5002"

  bcause_solver:
    build:
      context: .
      dockerfile: ./src/solvers/bcause_solver/Dockerfile
    volumes:
      - ./data:/app/data
    ports:
      - "5003:5003"

  autobounds_solver:
    build:
      context: .
      dockerfile: ./src/solvers/autobounds_solver/Dockerfile
    volumes:
      - ./data:/app/data
    ports:
      - "5004:5004"